### ISSUE TITLE
Nice work!

### ISSUE THREAD

**Issue by barrydegraaff** [iomarmochtar/zmbr_check_sender#1]
This is an interesting repo and [blog](https://iomarmochtar.wordpress.com/2017/09/13/zimbra-prevent-user-customizing-from-header/).

I wonder why you had this problem, is setting zimbraAllowAnyFromAddress to FALSE not an easier way to achieve this?

Also Zimbra has a built-in milter.

But, I still like to thank you for putting this on Github with the blog, as the Zimbra milter is very much undocumented. And this allows for much more flexible filtering. Thanks!

**Comment by iomarmochtar** [comment]
> I wonder why you had this problem, is setting zimbraAllowAnyFromAddress to FALSE not an easier way to achieve this?

Yes i've been try that before but not solving the issue. as in my post in zimbra forum [zimbra forum ](https://forums.zimbra.org/viewtopic.php?t=62676), you can try with testing script within this repo to your zimbra.

it's a honor to me, chief of zetalliance visit and commenting my simple repo  👍

**Comment by barrydegraaff** [comment]
OK we had a discussion on why the zimbraAllowAnyFromAddress does not work on the mailing list 

If you are not subscribed you can read it here: 
https://lists.zetalliance.org/pipermail/users_lists.zetalliance.org/2017-November/thread.html 



Kind regards, 

Barry de Graaff 
Zeta Alliance Founder 
zetalliance.org | github.com/Zimbra-Community 

+31 617 220 227 
Fingerprint: 97f4694a1d9aedad012533db725ddd156d36a2d0

**Comment by iomarmochtar** [comment]
Let them try the [testing script](https://github.com/iomarmochtar/zmbr_check_sender/blob/master/test/tes_sasl.py). 

previously i have comparing with microsoft exchange, it's successfully blocking (by it's default mail policy) and allowing which has the "send as" privileges. 

this issue was coming from the supperiority of authenticated user in zimbra's postfix can easily set email header.
